//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valutech.Electrox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Valutech.Electrox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///  &lt;LaserList&gt;
        ///    
        ///    &lt;LaserEquipment&gt;
        ///      &lt;Name&gt;Laser 1&lt;/Name&gt;
        ///      &lt;Ip&gt;10.2.16.201&lt;/Ip&gt;
        ///      &lt;Dsp&gt;LaserMarker1 - MaxBox&lt;/Dsp&gt;
        ///      &lt;Lens&gt;S254&lt;/Lens&gt;
        ///      &lt;DspFile&gt;\\file-server\files\49_ENG_TOOLS\Tools\Electrox Laser\DSP Parameters\LaserMarker1 - MaxBox.dsp&lt;/DspFile&gt;
        ///      &lt;Mru1&gt;&lt;/Mru1&gt;
        ///      &lt;Mru2&gt;&lt;/Mru2&gt;
        ///      &lt;Mru3&gt;&lt;/Mru3&gt;
        ///      &lt;Mru4&gt;&lt;/Mru4&gt;
        ///      &lt;Mru5&gt;&lt;/Mru5&gt;
        ///      &lt;Mru6&gt;&lt;/Mru6&gt;
        ///      &lt;Mru7&gt;&lt;/Mru7&gt;
        ///      &lt;Mru8&gt;&lt;/Mru8&gt;
        ///      &lt;Mru9&gt;&lt;/Mru9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LasersList {
            get {
                return ResourceManager.GetString("LasersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
